version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Map Nginx's port 80 to local port 5173 (not 3000)
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile  # Assuming your backend Dockerfile is named 'Dockerfile'
    ports:
      - "8080:8080"  # Expose backend on port 8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"  # Expose Redis on port 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
